# Generated by Django 6.1 on 2026-09-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('num_solicitacao', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pendente', max_length=50)),
            ],
        ),
    ]
