# Generated by Django 6.1 on 2026-09-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_ocorrencia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em análise', 'Em análise'), ('Em andamento', 'Em andamento'), ('Concluída', 'Concluída')], default='Pendente', max_length=50),
        ),
    ]
